# Generated by Django 5.0.14 on 2026-06-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(max_length=50, verbose_name='联系人')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('company', models.CharField(blank=True, default='', max_length=100, verbose_name='公司/品牌')),
                ('project_type', models.CharField(blank=True, choices=[('', '请选择项目类型'), ('full_house', '全屋定制'), ('hotel', '酒店工程'), ('showroom', '样板间/售楼处'), ('office', '办公空间'), ('restaurant', '餐饮门店'), ('club', '会所/别墅'), ('single', '单件定制'), ('other', '其他')], default='', max_length=30, verbose_name='项目类型')),
                ('quantity', models.CharField(blank=True, choices=[('', '请选择预计数量'), ('1-10', '1-10件'), ('10-50', '10-50件'), ('50-100', '50-100件'), ('100-500', '100-500件'), ('500+', '500件以上')], default='', max_length=20, verbose_name='预计数量')),
                ('city', models.CharField(blank=True, default='', max_length=50, verbose_name='交付城市')),
                ('budget', models.CharField(blank=True, choices=[('', '请选择预算区间'), ('under_50k', '5万以下'), ('50k_100k', '5-10万'), ('100k_300k', '10-30万'), ('300k_500k', '30-50万'), ('500k_1m', '50-100万'), ('1m_3m', '100-300万'), ('over_3m', '300万以上')], default='', max_length=20, verbose_name='预算区间')),
                ('description', models.TextField(blank=True, default='', verbose_name='需求说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
            ],
            options={
                'verbose_name': '客户咨询',
                'verbose_name_plural': '客户咨询',
                'db_table': 'contract',
                'ordering': ['-created_at'],
            },
        ),
    ]
