# Generated by Django 5.0.14 on 2026-06-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('new', '新提交'), ('contacted', '已联系'), ('dealing', '洽谈中'), ('done', '已成交'), ('invalid', '无效')], default='new', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
