# Generated by Django 5.0.14 on 2026-06-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_contract_status_alter_contract_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('case_type', models.CharField(blank=True, default='', max_length=30, verbose_name='项目类型')),
                ('area', models.CharField(blank=True, default='', max_length=30, verbose_name='面积')),
                ('style', models.CharField(blank=True, default='', max_length=30, verbose_name='风格')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('cover_image', models.CharField(blank=True, default='', max_length=500, verbose_name='封面图URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='展示')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '定制案例',
                'verbose_name_plural': '定制案例',
                'db_table': 'custom_case',
                'ordering': ['sort', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='产品名称')),
                ('code', models.CharField(max_length=30, verbose_name='产品编号')),
                ('category', models.CharField(choices=[('living', '客厅系列'), ('dining', '餐厅系列'), ('bedroom', '卧室系列'), ('study', '书房系列'), ('hotel', '酒店工程'), ('office', '办公系列')], max_length=20, verbose_name='品类')),
                ('material', models.CharField(blank=True, default='', max_length=200, verbose_name='材质')),
                ('size', models.CharField(blank=True, default='', max_length=100, verbose_name='尺寸')),
                ('price', models.CharField(blank=True, default='', max_length=50, verbose_name='参考价格')),
                ('description', models.CharField(blank=True, default='', max_length=300, verbose_name='简介')),
                ('features', models.TextField(blank=True, default='', verbose_name='产品特性')),
                ('is_active', models.BooleanField(default=True, verbose_name='上架')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
                'db_table': 'product',
                'ordering': ['sort', '-created_at'],
            },
        ),
    ]
