# Generated by Django 5.0.14 on 2026-06-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_customcase_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomCase',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AlterField(
            model_name='contract',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('new', '新提交'), ('contacted', '已联系'), ('negotiating', '洽谈中'), ('confirmed', '已确认'), ('closed', '已关闭')], default='new', max_length=20, verbose_name='状态'),
        ),
    ]
