# Generated by Django 5.0.14 on 2026-06-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0004_delete_customcase_delete_product_alter_contract_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(max_length=50, verbose_name='收货人')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('address', models.CharField(max_length=200, verbose_name='收货地址')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
                ('items', models.TextField(help_text='JSON 格式存储', verbose_name='购买明细')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='订单总额')),
                ('status', models.CharField(choices=[('new', '新订单'), ('confirmed', '已确认'), ('shipped', '已发货'), ('delivered', '已签收'), ('cancelled', '已取消')], default='new', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
            ],
            options={
                'verbose_name': '成品订单',
                'verbose_name_plural': '成品订单',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
