# Generated by Django 5.0.14 on 2026-06-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0005_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='型号')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('category', models.CharField(choices=[('living', '客厅'), ('dining', '餐厅'), ('bedroom', '卧室'), ('study', '书房'), ('office', '办公')], max_length=20, verbose_name='分类')),
                ('material', models.CharField(blank=True, default='', max_length=200, verbose_name='材质')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('desc', models.CharField(blank=True, default='', max_length=200, verbose_name='描述')),
                ('tag', models.CharField(blank=True, default='', help_text='如：热卖、新品', max_length=20, verbose_name='标签')),
                ('is_active', models.BooleanField(default=True, verbose_name='上架')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '成品商品',
                'verbose_name_plural': '成品商品',
                'db_table': 'products',
                'ordering': ['category', 'code'],
            },
        ),
    ]
