# Generated by Django 5.0.14 on 2026-06-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0006_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/', verbose_name='产品图片'),
        ),
    ]
