# Generated by Django 5.0.14 on 2026-06-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0009_product_details_product_size_alter_contract_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('case_type', models.CharField(choices=[('full_house', '全屋定制'), ('club', '会所家具'), ('villa', '别墅定制'), ('hotel', '酒店工程'), ('office', '办公定制'), ('garden', '庭院家具')], max_length=30, verbose_name='项目类型')),
                ('area', models.CharField(max_length=30, verbose_name='面积')),
                ('style', models.CharField(max_length=30, verbose_name='风格')),
                ('desc', models.TextField(verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='展示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '定制案例',
                'verbose_name_plural': '定制案例',
                'db_table': 'custom_cases',
                'ordering': ['-created_at'],
            },
        ),
    ]
