# Generated by Django 5.0.14 on 2026-06-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0010_customcase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='品牌名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='展示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '合作品牌',
                'verbose_name_plural': '合作品牌',
                'db_table': 'partners',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='客户名称')),
                ('role', models.CharField(max_length=100, verbose_name='身份')),
                ('text', models.TextField(verbose_name='评价内容')),
                ('is_active', models.BooleanField(default=True, verbose_name='展示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '客户评价',
                'verbose_name_plural': '客户评价',
                'db_table': 'testimonials',
            },
        ),
    ]
