# Generated by Django 5.0.14 on 2026-06-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0011_partner_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Craft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=5, verbose_name='步骤编号')),
                ('title', models.CharField(max_length=50, verbose_name='步骤名称')),
                ('desc', models.TextField(verbose_name='详细描述')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '工艺流程',
                'verbose_name_plural': '工艺流程',
                'db_table': 'crafts',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='车间名称')),
                ('area', models.CharField(max_length=30, verbose_name='面积')),
                ('workers', models.IntegerField(default=0, verbose_name='工人数')),
                ('equip', models.TextField(verbose_name='设备清单')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='展示')),
            ],
            options={
                'verbose_name': '工厂车间',
                'verbose_name_plural': '工厂车间',
                'db_table': 'workshops',
                'ordering': ['sort'],
            },
        ),
    ]
