# Generated by Django 5.0.14 on 2026-06-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0012_craft_workshop'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='问题')),
                ('answer', models.TextField(verbose_name='答案')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='展示')),
            ],
            options={
                'verbose_name': '常见问题',
                'verbose_name_plural': '常见问题',
                'db_table': 'faqs',
                'ordering': ['sort'],
            },
        ),
    ]
