# Generated by Django 5.0.14 on 2026-06-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0014_category_alter_contract_id_alter_craft_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='尚品工坊', max_length=100, verbose_name='公司名称')),
                ('phone', models.CharField(default='400-888-6688', max_length=30, verbose_name='联系电话')),
                ('email', models.CharField(default='info@shangpin.com', max_length=50, verbose_name='联系邮箱')),
                ('address', models.CharField(default='广东省佛山市顺德区龙江镇工业大道188号', max_length=200, verbose_name='公司地址')),
                ('hero_title', models.CharField(default='以工艺之名\n定义家居美学', max_length=100, verbose_name='首页主标题')),
                ('hero_sub', models.CharField(blank=True, default='二十三年专注高端家具制造\n从原木到成品，每一件都是对品质的承诺', max_length=200, verbose_name='首页副标题')),
            ],
            options={
                'verbose_name': '站点配置',
                'verbose_name_plural': '站点配置',
            },
        ),
    ]
