# Generated by Django 5.0.14 on 2026-06-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0016_announcement_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_title', models.CharField(default='', max_length=100)),
                ('home_desc', models.TextField(blank=True, default='')),
                ('products_title', models.CharField(default='', max_length=100)),
                ('products_desc', models.TextField(blank=True, default='')),
                ('shop_title', models.CharField(default='', max_length=100)),
                ('shop_desc', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'SEO 配置',
                'verbose_name_plural': 'SEO 配置',
                'db_table': 'seo_config',
            },
        ),
    ]
