# Generated by Django 5.0.14 on 2026-06-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0017_seoconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='名称')),
                ('key', models.CharField(max_length=30, unique=True, verbose_name='英文标识')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '购买分类',
                'verbose_name_plural': '购买分类',
                'db_table': 'shop_categories',
                'ordering': ['sort'],
            },
        ),
    ]
