# Generated by Django 5.0.14 on 2026-06-16 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0018_shopcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shop_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='editor.shopcategory', verbose_name='购买分类'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='editor.category', verbose_name='产品分类'),
        ),
    ]
