# Generated by Django 5.0.14 on 2026-06-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0019_product_shop_category_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='描述'),
        ),
    ]
