# Generated by Django 5.0.14 on 2026-06-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0020_category_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='categories/', verbose_name='分类图片'),
        ),
    ]
