"""
Django settings for image_editor project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

BASE_DIR = Path(__file__).resolve().parent.parent

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-a2_texzipog9d*uz7t1wk#6_%%&4y+j$&75_g8#fga^80u9#ua')
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'
ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', '*').split(',')


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'editor',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'image_editor.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'image_editor.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Media files (uploaded images)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# CORS
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://localhost:5174',
    'http://localhost:5175',
    'http://127.0.0.1:5173',
    'http://127.0.0.1:5174',
    'http://127.0.0.1:5175',
]
CORS_ALLOW_CREDENTIALS = True

# SimpleUI 自定义配置
SIMPLEUI_DEFAULT_THEME = 'simpleui.css'
SIMPLEUI_STATIC_OFFLINE = True
SIMPLEUI_HOME_INFO = False
SIMPLEUI_ANALYSIS = False
SIMPLEUI_TITLE = '尚品工坊 管理后台'
SIMPLEUI_HEADER = '尚品工坊'
SIMPLEUI_INDEX = 'http://localhost:5173'
SIMPLEUI_HOME_URL = 'http://localhost:5173'
SIMPLEUI_HOME_TITLE = '返回官网首页'
SIMPLEUI_LOGO = ''
SIMPLEUI_CONFIG = {
    'system_keep': False,
    'menu_display': ['成品管理', '内容管理', '联系表单', '认证和授权'],
    'menus': [
        {
            'name': '成品管理',
            'icon': 'fas fa-shopping-cart',
            'models': [
                {
                    'name': '分类管理',
                    'icon': 'fas fa-tags',
                    'url': '/admin/editor/category/',
                },
                {
                    'name': '购买分类',
                    'icon': 'fas fa-tag',
                    'url': '/admin/editor/shopcategory/',
                },
                {
                    'name': '商品管理',
                    'icon': 'fas fa-box',
                    'url': '/admin/editor/product/',
                },
                {
                    'name': '成品订单',
                    'icon': 'fas fa-clipboard-list',
                    'url': '/admin/editor/order/',
                },
            ],
        },
        {
            'name': '内容管理',
            'icon': 'fas fa-pen',
            'models': [
                {
                    'name': '合作品牌',
                    'icon': 'fas fa-handshake',
                    'url': '/admin/editor/partner/',
                },
                {
                    'name': '客户评价',
                    'icon': 'fas fa-star',
                    'url': '/admin/editor/testimonial/',
                },
                {
                    'name': '定制案例',
                    'icon': 'fas fa-building',
                    'url': '/admin/editor/customcase/',
                },
                {
                    'name': '工厂车间',
                    'icon': 'fas fa-industry',
                    'url': '/admin/editor/workshop/',
                },
                {
                    'name': '工艺流程',
                    'icon': 'fas fa-cogs',
                    'url': '/admin/editor/craft/',
                },
                {
                    'name': '网站公告',
                    'icon': 'fas fa-bullhorn',
                    'url': '/admin/editor/announcement/',
                },
                {
                    'name': '首页轮播',
                    'icon': 'fas fa-images',
                    'url': '/admin/editor/banner/',
                },
                {
                    'name': '站点配置',
                    'icon': 'fas fa-cog',
                    'url': '/admin/editor/siteconfig/1/change/',
                },
            ],
        },
        {
            'name': '联系表单',
            'icon': 'fas fa-envelope',
            'models': [
                {
                    'name': '客户咨询',
                    'icon': 'fas fa-list-alt',
                    'url': '/admin/editor/contract/',
                },
            ],
        },
        {
            'name': '认证和授权',
            'icon': 'fas fa-user-shield',
            'models': [
                {
                    'name': '管理员管理',
                    'icon': 'fas fa-user-tie',
                    'url': '/admin/auth/user/?is_staff__exact=1',
                },
                {
                    'name': '用户管理',
                    'icon': 'fas fa-user',
                    'url': '/admin/auth/user/?is_staff__exact=0',
                },
                {
                    'name': '组管理',
                    'icon': 'fas fa-users',
                    'url': '/admin/auth/group/',
                },
            ],
        },
    ],
}

# REST Framework + JWT
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=2),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'AUTH_HEADER_TYPES': ('Bearer',),
}
